# Configuration file for build process

CFLAGS = -Wall -Wextra
CFLAGS += -std=c11
CFLAGS += -Og

LEXER = flex
PARSER = bison

LEXERFLAGS = --header-file=src/tokenize.h -o src/lexer.c
PARSERFLAGS = -d -o src/parser.c -p parser parser.y

TOKENIZE = src/tokenize.h
PARSE = src/parser.c

# Rule to compile lexer
lexer: src/lexer.c
	@echo "Compiling lexer..."
	@$(LEXER) $(LEXERFLAGS) lexer.l
	@echo "Lexer compiled."

# Rule to compile parser
parser: src/parser.c
	@echo "Compiling parser..."
	@$(PARSER) $(PARSERFLAGS)
	@echo "Parser compiled."

# Rule to build the compiler
compiler: lexer parser src/emitter.c src/main.c
	@echo "Building the compiler..."
	@$(CC) $(CFLAGS) -o ./bin/mini-c-compiler src/emitter.c src/main.c src/lexer.c src/parser.c
	@echo "Compiler built."

# Rule to run tests
tests: tests/test_lexer.c tests/test_parser.c tests/test_semantics.c tests/test_emitter.c
	@echo "Running tests..."
	@$(CC) $(CFLAGS) -o tests/test_lexer tests/test_lexer.c
	@$(CC) $(CFLAGS) -o tests/test_parser tests/test_parser.c
	@$(CC) $(CFLAGS) -o tests/test_semantics tests/test_semantics.c
	@$(CC) $(CFLAGS) -o tests/test_emitter tests/test_emitter.c
	@echo "Tests finished."

# Rule to clean the build directory
clean:
	@echo "Cleaning build directory..."
	@rm -f ./bin/mini-c-compiler src/*.c tests/*.c tests/*.o
	@echo "Build directory cleaned."

# Rule to build the project
all: lexer parser compiler tests
	@echo "Project built."